# environment.yml

name: cs337_proj2
channels:
  - defaults
  - conda-forge
dependencies:
  - annotated-types=0.6.0=py310hca03da5_1
  - beautifulsoup4=4.13.5=py310hca03da5_0
  - blas=1.0=openblas
  - brotlicffi=1.0.9.2=py310h50f4ffc_2
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - catalogue=2.0.10=py310hca03da5_0
  - certifi=2025.11.12=py310hca03da5_0
  - cffi=2.0.0=py310h73c2a22_1
  - charset-normalizer=3.4.4=py310hca03da5_0
  - click=8.2.1=py310hca03da5_0
  - cloudpathlib=0.21.0=py310hca03da5_0
  - colorama=0.4.6=py310hca03da5_0
  - confection=0.1.5=py310hd096484_0
  - cymem=2.0.11=py310h0962b89_0
  - cython-blis=1.0.1=py310h80987f9_0
  - expat=2.7.3=h982b769_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=py310hca03da5_0
  - jinja2=3.1.6=py310hca03da5_0
  - langcodes=3.5.0=py310hca03da5_0
  - language-data=1.3.0=py310hca03da5_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.30=hf2bb037_2
  - libsqlite=3.51.0=h8adb53f_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - marisa-trie=1.3.1=py310h0962b89_0
  - markdown-it-py=4.0.0=py310hca03da5_0
  - markupsafe=3.0.2=py310h80987f9_0
  - mdurl=0.1.2=py310hca03da5_0
  - murmurhash=1.0.12=py310h313beb8_0
  - ncurses=6.5=hee39554_0
  - numpy=2.2.5=py310h40d09ce_2
  - numpy-base=2.2.5=py310h855c928_2
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=py310hca03da5_1
  - pip=25.2=pyhc872135_1
  - preshed=3.0.9=py310h313beb8_0
  - pycparser=2.23=py310hca03da5_0
  - pydantic=2.12.3=py310hca03da5_1
  - pydantic-core=2.41.4=py310h108b7f8_0
  - pygments=2.19.2=py310hca03da5_0
  - pysocks=1.7.1=py310hca03da5_1
  - python=3.10.15=hdce6c4c_2_cpython
  - python_abi=3.10=8_cp310
  - rapidfuzz=3.14.3=py310hc7786af_1
  - readline=8.3=h0b18652_0
  - requests=2.32.5=py310hca03da5_1
  - rich=13.9.4=py310hca03da5_0
  - setuptools=80.9.0=py310hca03da5_0
  - shellingham=1.5.4=py310hca03da5_0
  - smart_open=7.3.1=py310hca03da5_0
  - soupsieve=2.5=py310hca03da5_0
  - spacy=3.8.7=py310h558c740_0
  - spacy-legacy=3.0.12=py310hca03da5_0
  - spacy-loggers=1.0.4=py310hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - srsly=2.5.1=py310h313beb8_0
  - thinc=8.3.2=py310h48ca7d4_1
  - tk=8.6.15=hcd8a7d5_0
  - tqdm=4.67.1=py310h7eb115d_1
  - typer=0.9.0=py310hca03da5_0
  - typing-extensions=4.15.0=py310hca03da5_0
  - typing-inspection=0.4.2=py310hca03da5_0
  - typing_extensions=4.15.0=py310hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py310hca03da5_0
  - wasabi=1.1.3=py310hca03da5_0
  - weasel=0.4.1=py310hca03da5_0
  - wheel=0.45.1=py310hca03da5_0
  - wrapt=1.17.0=py310h80987f9_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - en-core-web-sm==3.8.0
prefix: /Users/tadeo/anaconda3/envs/cs337_proj2
