name: cs337_proj2
channels:
  - defaults
dependencies:
  - beautifulsoup4=4.13.5
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - expat=2.7.3
  - idna=3.11
  - libcxx=20.1.8
  - libffi=3.4.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.2
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.10.19
  - readline=8.3
  - requests=2.32.5
  - setuptools=80.9.0
  - soupsieve=2.5
  - sqlite=3.51.0
  - tk=8.6.15
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
prefix: /Users/tadeo/anaconda3/envs/cs337_proj2
